# Generated by Django 4.0.1 on 2022-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tachersprofiles',
            name='pic',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
