# Generated by Django 4.0.1 on 2022-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TachersProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70, null=True, unique=True)),
                ('info', models.TextField()),
                ('level', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
