# Generated by Django 4.0.1 on 2022-02-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_payment_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
