# Generated by Django 4.0.1 on 2022-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_tklifanswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tklifanswer',
            name='ansser',
            field=models.FileField(upload_to='tklifanser/', verbose_name='جواب سوال'),
        ),
    ]
