# Generated by Django 4.0.1 on 2022-04-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_quiz_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pic',
            field=models.FileField(upload_to='images/'),
        ),
    ]
