# Generated by Django 4.0.1 on 2022-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesales',
            name='uploadcourse',
            field=models.FileField(default=1, upload_to='CourseSales/'),
            preserve_default=False,
        ),
    ]
