# Generated by Django 4.0.1 on 2022-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_tklif_courses_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
