# Generated by Django 4.0.1 on 2022-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_payment_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
